services:
  borough:
    image: medium:v1
    secrets:
      - db_url
    ports:
      - "4000:8888"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 30s
        order: stop-first
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8888/health || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 30s
secrets:
  db_url:
    external: true
